# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Upload Release Asset

on:
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build and Upload Release Asset
    runs-on: windows-latest 
    steps:
      - name: Print GitHub workspace path
        run: echo $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.100'
      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short=8 $GITHUB_SHA)"
      - name: Build project
        run: dotnet build -c Release -p:SourceLinkCreate=true -p:PublishProfile=FolderProfile ReportSystem.csproj
      - name: Publish Artifact
        run: dotnet publish -c Release -o ./publish -p:SourceLinkCreate=true -p:PublishProfile=FolderProfile ReportSystem.csproj
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit_hash.outputs.hash }}
          release_name: v123  # Use a fixed release name or modify as needed
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $GITHUB_WORKSPACE
          asset_name: test.zip
          asset_content_type: application/zip
